---
title: "R Notebook"
output: html_notebook
---

```{r}
load("/Volumes/Research Project/Self-Anchoring/Combined/Combined/reportingAnalysesEnv.RData")
```
```{r}
library(pacman)
p_load(tidyverse, ggdist, wesanderson, patchwork, brms)
```

```{r}
library(bayestestR)
ps1 <- bayestestR::p_significance(WSRNOV.ING)
plot(ps1) + jtools::theme_apa() + scale_y_discrete(labels = c("Similarity-to-Self\nX Novel","Novel","Similarity-to-Self")) + xlab(expression(beta)) + ylab("Fixed Effects")
```


# Study 2

## Warmth

```{r}
warmthDf <- pivot_longer(indDiffs2, cols=starts_with("Therm_"), names_to="University", values_to="Warmth") %>% select(subID, University, Warmth) %>% drop_na()
warmthDf$University <- gsub("Therm_1","UCR", warmthDf$University)
warmthDf$University <- gsub("Therm_2","UCLA", warmthDf$University)
warmthDf$University <- gsub("Therm_4","CSU LA", warmthDf$University)

warmPlot2 <- ggplot(warmthDf, aes(University, Warmth)) + 
  ggdist::stat_halfeye(adjust = .5, width = .7, .width = 0, justification = -.2, point_colour = NA) + 
  geom_boxplot(width = .2, outlier.shape = NA)  + scale_x_discrete(labels=c("Lower Status\nOutgroup","Higher Status\nOutgroup", "Ingroup")) +
  geom_jitter(width = .05, alpha = .15) + labs(y="Perceived Warmth",x="University") + jtools::theme_apa()
```

## Status

```{r}
indDiffs2$Status <- NULL
statusDf <- pivot_longer(indDiffs2, cols=ends_with("_Status"), names_to="University", values_to="Status") %>% select(subID, University, Status) %>% drop_na()
statusDf$University <- gsub("_Status","", statusDf$University)

statusDf$University <- as.factor(statusDf$University)
statusDf$subID <- as.factor(statusDf$subID)

statusPlot2 <- ggplot(statusDf, aes(University, Status)) + 
  ggdist::stat_halfeye(adjust = .5, width = .7, .width = 0, justification = -.2, point_colour = NA) + 
  geom_boxplot(width = .2, outlier.shape = NA) + scale_x_discrete(labels=c("Lower Status\nOutgroup","Higher Status\nOutgroup", "Ingroup")) +
  geom_jitter(width = .05, alpha = .15) + labs(y="Perceived Status",x="University") + jtools::theme_apa()
```

## Combine Warmth and Status Plots

```{r}
wsPlot2 <- warmPlot2 + statusPlot2 
wsPlot2
```

## Metacontrast Ratio

```{r}
MCS.SR.COND.2.p <- conditional_effects(MCS.SR.COND.2, method = "posterior_linpred")
MCS.SR.COND.2.p_ <- MCS.SR.COND.2.p$`metaContrastS.Z:outgroup`
MCS.SR.COND.2.MCRplot <-ggplot(MCS.SR.COND.2.p_, aes(effect1__, estimate__)) +  geom_line(aes(linetype=effect2__, color=effect2__)) + 
  geom_ribbon(aes(ymin=lower__, ymax=upper__, fill=effect2__), alpha=0.15) + 
  scale_linetype_discrete(labels = c("Negation","Lower Status","Higher Status")) + 
  scale_color_manual(labels = c("Negation","Lower Status","Higher Status"), values = wes_palette("Darjeeling1")) + 
  scale_fill_manual( 
                      labels=c("Negation","Lower Status","Higher Status"), values = wes_palette("Darjeeling1")) + 
  theme(
    legend.position = c(.4, .7),
    legend.justification = c("left", "bottom"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    ) + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold")) + theme(legend.text = element_text(size=12)) + theme(panel.border = element_rect(colour = "black", fill = NA, size =1)) + theme(legend.title = element_blank()) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  xlab("Metacontrast Ratio") + ylab("Self-Evaluation")
MCS.SR.COND.2.MCRplot
```


## Summed Similarity to Outgroup Compared Across Conditions

```{r}
ISOS.SR.COND.2.p <- conditional_effects(ISOS.SR.COND.2, method = "posterior_linpred")
ISOS.SR.COND.2.p_ <- ISOS.SR.COND.2.p$`outGsimS.Z:outgroup`
ISOS.SR.COND.2.OutGplot <-ggplot(ISOS.SR.COND.2.p_, aes(effect1__, estimate__)) +  geom_line(aes(linetype=effect2__, color=effect2__)) + 
  geom_ribbon(aes(ymin=lower__, ymax=upper__, fill=effect2__), alpha=0.15) + 
  scale_linetype_discrete(labels = c("Negation","Lower Status","Higher Status")) + 
  scale_color_manual(labels = c("Negation","Lower Status","Higher Status"), values = wes_palette("Darjeeling1")) + 
  scale_fill_manual( 
                      labels=c("Negation","Lower Status","Higher Status"), values = wes_palette("Darjeeling1")) + 
  theme(
    legend.position = c(.4, .7),
    legend.justification = c("left", "bottom"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    ) + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold")) + theme(legend.text = element_text(size=12)) + theme(panel.border = element_rect(colour = "black", fill = NA, size =1)) + theme(legend.title = element_blank()) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  xlab("Similarity-to-Outgroup") + ylab("Self-Evaluation")
ISOS.SR.COND.2.OutGplot
```

# Study 3

## Warmth

```{r}
warmthDf3 <- pivot_longer(indDiffs3, cols=starts_with("Therm_"), names_to="Group", values_to="Warmth") %>% select(subID, Group, Warmth) %>% drop_na()
warmthDf3$Group <- gsub("Therm_1","White", warmthDf3$Group)
warmthDf3$Group <- gsub("Therm_2","Asian", warmthDf3$Group)
warmthDf3$Group <- gsub("Therm_4","Latino", warmthDf3$Group)

warmthDf3$Group <- as.factor(warmthDf3$Group)
warmthDf3$subID <- as.factor(warmthDf3$subID)

warmPlot3 <- ggplot(warmthDf3, aes(Group, Warmth)) + 
  ggdist::stat_halfeye(adjust = .5, width = .7, .width = 0, justification = -.2, point_colour = NA) + 
  geom_boxplot(width = .2, outlier.shape = NA) + 
  geom_jitter(width = .05, alpha = .15) + labs(y="Perceived Warmth",x="Racial Group") + jtools::theme_apa()
```

## Status

```{r}
indDiffs3$Status <- NULL
statusDf3 <- pivot_longer(indDiffs3, cols=ends_with("_Status"), names_to="Group", values_to="Status") %>% select(subID, Group, Status) %>% drop_na()
statusDf3$Group <- gsub("_Status","", statusDf3$Group)

statusDf3$Group <- as.factor(statusDf3$Group)
statusDf3$subID <- as.factor(statusDf3$subID)

statusPlot3 <- ggplot(statusDf3, aes(Group, Status)) + 
  ggdist::stat_halfeye(adjust = .5, width = .7, .width = 0, justification = -.2, point_colour = NA) + 
  geom_boxplot(width = .2, outlier.shape = NA) + 
  geom_jitter(width = .05, alpha = .3) + labs(y="Perceived Status",x="Racial Group") + jtools::theme_apa()
```

## Combine Warmth and Status Plots

```{r}
wsPlot3 <- warmPlot3 + statusPlot3
wsPlot3
```

## Metacontrast Ratio

```{r}
MCS.SR.COND.3.p <- conditional_effects(MCS.SR.COND.3)
MCS.SR.COND.3.p_ <- MCS.SR.COND.3.p$`metaContrastS.Z:condition`
MCS.SR.COND.3.MCRplot <-ggplot(MCS.SR.COND.3.p_, aes(effect1__, estimate__)) +  geom_line(aes(linetype=effect2__, color=effect2__)) + geom_ribbon(aes(ymin=lower__, ymax=upper__, fill=effect2__), alpha=0.15) + scale_linetype_discrete(labels = c("Majority","Minority")) + scale_color_manual(labels = c("Majority","Minority"), values = c("#44AA99","#332288")) + scale_fill_manual( 
                      labels=c("Majority","Minority"), values = c("#44AA99","#332288")) + theme(
    legend.position = c(.4, .7),
    legend.justification = c("left", "bottom"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    ) + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold")) + theme(legend.text = element_text(size=12)) + theme(panel.border = element_rect(colour = "black", fill = NA, size =1)) + theme(legend.title = element_blank()) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  xlab("Metacontrast Ratio") + ylab("Self-Evaluation")
MCS.SR.COND.3.MCRplot
```


## Summed Similarity to Outgroup Compared Across Conditions

```{r}
ISOS.SR.COND.3.p <- conditional_effects(ISOS.SR.COND.3)
ISOS.SR.COND.3.p_ <- ISOS.SR.COND.3.p$`outGsimS.Z:condition`
ISOS.SR.COND.3.OutGPlot <-ggplot(ISOS.SR.COND.3.p_, aes(effect1__, estimate__)) +  geom_line(aes(linetype=effect2__, color=effect2__)) + geom_ribbon(aes(ymin=lower__, ymax=upper__, fill=effect2__), alpha=0.15) + scale_linetype_discrete(labels = c("Majority","Minority")) + scale_color_manual(labels = c("Majority","Minority"), values = c("#44AA99","#332288")) + scale_fill_manual( 
                      labels=c("Majority","Minority"), values = c("#44AA99","#332288")) + theme(
    legend.position = c(.4, .7),
    legend.justification = c("left", "bottom"),
    legend.box.just = "left",
    legend.margin = margin(6, 6, 6, 6)
    ) + theme(axis.text=element_text(size=12),
        axis.title=element_text(size=12,face="bold")) + theme(legend.text = element_text(size=12)) + theme(panel.border = element_rect(colour = "black", fill = NA, size =1)) + theme(legend.title = element_blank()) + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_blank(), axis.line = element_line(colour = "black")) +
  xlab("Similarity-to-Outgroup") + ylab("Self-Evaluation")
ISOS.SR.COND.3.OutGPlot
```

# Studies Combined

```{r}
wsPlot23 <- wsPlot2 / wsPlot3
wsPlot23
```

