---
title: "R Notebook"
output: html_notebook
---

```{r}
fullTest <- read.csv("./Study 1/Cleaning/output/fullTest.csv")
fullTrain <- read.csv("./Study 1//Cleaning/output/fullTrain.csv")

traitsFreqs <- read.csv("./Study 1/Cleaning/output/traitFreqOverUnder.csv")


uSubs <- unique(fullTest$subID)

indDiffs <- fullTest[!duplicated(fullTest$subID),]
indDiffs <- indDiffs %>% select(subID, groupHomoph, DS:SING.Inter)

fullTrain <- merge(fullTrain, indDiffs, by = "subID")

fullTrain$metaContrast <- fullTrain$inGsim / fullTrain$outGsim

fullTest$ingChoiceN <- as.factor(fullTest$ingChoiceN)
fullTest$novel <- as.factor(fullTest$novel)
fullTest$selfResp.Z <- scale(fullTest$selfResp)
fullTest$SE.Z <- scale(fullTest$SE)
fullTest$iSE.Z <- scale(fullTest$iSE)
fullTest$oSE.Z <- scale(fullTest$oSE)
fullTest$predicted.Z <- scale(fullTest$predicted)
fullTest$slope.Z <- scale(fullTest$slope)
fullTest$entropy.Z <- scale(fullTest$entropy)
fullTest$WSR.Z <- scale(fullTest$WSR)
fullTest$neighAveOutSE.Z <- scale(fullTest$neighAveOutSE)
fullTest$neighAveAllSE.Z <- scale(fullTest$neighAveAllSE)
fullTest$neighAveInSE.Z <- scale(fullTest$neighAveInSE)
fullTest$evalLOO.Z <- scale(fullTest$evalLOO)
fullTest$propCorrLOO.Z <- scale(fullTest$propCorrLOO)
fullTest$propCorr.Z <- scale(fullTest$propCorr)
fullTest$desirability.Z <- scale(fullTest$desirability)
fullTest$er.Z <- scale(fullTest$er)

fullTest$novel <- as.factor(fullTest$novel)
levels(fullTest$novel) <- list("Trained"  = "0", "Held Out" = "1")

fullTest1 <- fullTest
fullTrain1 <- fullTrain

fullTest1$outgroup <- "Minimal"
fullTest1$study <- "Study 1"

fullTrain1$outgroup <- "Minimal"
fullTrain1$study <- "Study 1"

fullTrain1$subID <- 50000
```

```{r}
fullTest <- arrow::read_parquet("./Study 2//Cleaning/output/fullTest.parquet")
fullTrain <- arrow::read_parquet("./Study 2/Cleaning/output/fullTrain.parquet")
traitsFreqs <- arrow::read_parquet("./Study 2/Cleaning/output/traitFreqOverUnder.parquet")

uSubs <- unique(fullTest$subID)

indDiffs <- fullTest[!duplicated(fullTest$subID),]

allPosCents <- read.csv("/Volumes/GoogleDrive/My Drive/Volumes/Research Project/Trait Network_Behaviral/generating network/output/allPosCents.csv")

fullTest$ingChoiceN <- as.factor(fullTest$ingChoiceN)
fullTest$novel <- as.factor(fullTest$novel)
fullTest$selfResp.Z <- scale(fullTest$selfResp)
fullTest$SE.Z <- scale(fullTest$SE)
fullTest$iSE.Z <- scale(fullTest$iSE)
fullTest$oSE.Z <- scale(fullTest$oSE)
fullTest$predicted.Z <- scale(fullTest$predicted)
fullTest$slope.Z <- scale(fullTest$slope)
fullTest$entropy.Z <- scale(fullTest$entropy)
fullTest$WSR.Z <- scale(fullTest$WSR)
fullTest$neighAveOutSE.Z <- scale(fullTest$neighAveOutSE)
fullTest$neighAveAllSE.Z <- scale(fullTest$neighAveAllSE)
fullTest$neighAveInSE.Z <- scale(fullTest$neighAveInSE)
fullTest$evalLOO.Z <- scale(fullTest$evalLOO)
fullTest$propCorrInLOO.Z <- scale(fullTest$propCorrInLOO)
fullTest$propCorrOutLOO.Z <- scale(fullTest$propCorrOutLOO)
#fullTest$propCorr.Z <- scale(fullTest$propCorr)
fullTest$desirability.Z <- scale(fullTest$desirability)
fullTest$er.Z <- scale(fullTest$er)
fullTest$inDegree.Z <- scale(fullTest$inDegree)
fullTest$outDegree.Z <- scale(fullTest$outDegree)
fullTest$Ent.Z <- scale(fullTest$Ent)

fullTest$outgroup <- as.factor(fullTest$outgroup)
fullTest$outgroup <- relevel(fullTest$outgroup,"Not UCR")

fullTest$outgroupE <- named.effects.ref(fullTest$outgroup, "Not UCR")

mat = matrix(c(1/3, 1/3, 1/3, -.5, 1, -.5, -.5, -.5, 1), nrow = 3)
mymat = solve(t(mat))
mymat
#remove the intercept (constant) term
my.contrasts<-mymat[,2:3]
colnames(my.contrasts) <- c("CSULA-Other", "UCLA-Other")
fullTest$outgroupU <- fullTest$outgroup
contrasts(fullTest$outgroupU) = my.contrasts


mycontrasts2 = contrasts(fullTest$outgroup)
mycontrasts2[,1] = c(-1/2, -1/2, 1)
mycontrasts2[,2] = c(-1/2, 1, -1/2)
contrasts(fullTest$outgroupU) = mycontrasts2

fullTest2 <- fullTest
fullTrain2 <- fullTrain

fullTest2$study <- "Study 2"
fullTrain2$study <- "Study 2"
```

```{r}
fullTest1r <- fullTest1 %>% select(subID, trait, ingChoiceN, WSR.Z, desirability.Z, study, outgroup)
fullTest2r <- fullTest2 %>% select(subID, trait, ingChoiceN, WSR.Z, desirability.Z, study, outgroup)
fullTestc <- rbind(fullTest1r, fullTest2r)
fullTestc$outgroup <- named.effects.ref(fullTestc$outgroup, "Minimal")
```

```{r}
m <- glmer( ingChoiceN ~ WSR.Z * outgroup + ( WSR.Z | subID ) + ( 1 | subID:study ) + ( outgroup | trait), data = fullTestc, family = binomial, control = glmerControl(optimizer = "bobyqa",
                                    optCtrl = list(maxfun = 100000)),
    nAGQ = 1)
tab_model(m, collapse.ci = T, show.stat=T, show.r2 = T, show.se = T, string.pred = c("Fixed Effects"), string.est = "OR", string.se = "SE", string.stat = "z", digits = 3, emph.p = F, dv.labels = "Ingroup Prediction")
ggpredict(m, c("WSR.Z", "outgroup")) %>% plot(show.title=F)
```


